### ISSUE TITLE
Package usable on the client side

### ISSUE THREAD

**Issue by green-coder** [peerlibrary/meteor-fs#3]
I am a beginner with Meteor and my question might be stupid, sorry in advance.

I am building a desktop app version of my meteor webapp using arboleya:electrify and I would like to access the files on the client side, as it is permitted via Electron.

It would be nice if you could modify your package so that it works on the client as well.

**Comment by mitar** [comment]
No, this is out of the scope of this package. This package just makes a standard node.js module to use fibers.
